### PR TITLE
Created New Flutter App

### LINKED ISSUE #95: A working prototype of the Flutter Frontend
- Test the "Flutter-App" contents. Those are 8 months old. Not tested since then.
- Contact the PA regarding the test results.
- After discussions, move forward to a working implementation of the Spotify clone on Flutter.

### PR DESCRIPTION
**Pull request by HimeshNayak**
Created a new flutter application named spotify_clone. 
Fixes #95

### CODE REVIEW

**Comment by forkbabu** [comment]
Hi @HimeshNayak , can you make this PR into the flutter branch. I'm creating a new branch with no contents where you I merge this entire app. Also, it would be beneficial if you share with me the UI of the app through a gdrive folder with all activity screenshots or by uploading it right here in the comments.

Thank you

**Comment by forkbabu** [comment]
@HimeshNayak Make sure you have these files -> https://github.com/ucalyptus/Spotify-Recommendation-Engine/tree/app or else you will get a merge conflict. The PR has to go to app branch and not master. Master is fr the ML part.

**Comment by forkbabu** [comment]
Ok. I changed the base branch to app.

**Review by forkbabu — APPROVED** [review]

**Comment by ucalyptus** [comment]
@HimeshNayak any updates?

**Comment by HimeshNayak** [comment]
Sorry for replying late. #95 was to create all the necessary files for a basic app to run. You can merge this PR. Now #96 can be started in which all the frontend of the app will be coded and then we can show you the screen shots of the app. We will be developing the frontend using this (https://github.com/ucalyptus/Spotify-Recommendation-Engine/tree/v0.1/Mockups/Snapshots) as reference.

**Pull request merged**
