### PR TITLE
Created CONTRIBUTE.md and resized step images

### PR DESCRIPTION
**Pull request by Mansi145**
Fixes issue #52 and #18.

### CODE REVIEW

**Comment by ucalyptus** [comment]
@Mansi145 update your PR as README has seen some changes.

**Comment by Mansi145** [comment]
@ucalyptus I've updated the PR. Can you have a look?

**Comment by ucalyptus** [comment]
@Mansi145 share a screenshot on how the images look now.

**Comment by ucalyptus** [comment]
Will merge just after that

**Comment by Mansi145** [comment]
@ucalyptus  These are some of the images that I resized. Will they work fine? Let me know of the changes if there are any.

Captdgewure
Capdsvhetture

**Pull request merged**
