### PR TITLE
Github Action workflows for Flutter

### PR DESCRIPTION
**Pull request by hpnightowl**
## Description

the changes are for github action workflow for flutter and also removes the deprecated workflows
Fixes # (https://github.com/ucalyptus/Spotify-Recommendation-Engine/issues/98)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- [X] Automated testing 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by forkbabu** [comment]
@hpnightowl your CI fails. Are you missing any Github key requirement?

**Comment by forkbabu** [comment]
@vilsi12 can you examine the code in the flutter branch ? I see that the CI is failing because of some dart errors. Follow [this link](https://github.com/ucalyptus/Spotify-Recommendation-Engine/pull/99/checks?check_run_id=1669018859) to find what errors are there.

**Comment by hpnightowl** [comment]
it fails because of the app i guess

**Comment by forkbabu** [comment]
> it fails because of the app i guess
> 
> This was caught by the test expectation on the following line:
> file:///home/runner/work/Spotify-Recommendation-Engine/Spotify-Recommendation-Engine/spotify_clone/test/widget_test.dart line 19
> The test description was:
> Counter increments smoke test

@hpnightowl noted.

**Comment by ucalyptus** [comment]
@vilsi12  pls check why the flutter ci is failing

**Comment by vilsi12** [comment]
Yes sir

**Comment by forkbabu** [comment]
@hpnightowl , @vilsi12 any updates?

**Comment by hpnightowl** [comment]
@forkbabu it Kinda app issue i guess since i use same flutter workflow for my app and works well :) but may be i may be wrong somewhere.

**Pull request closed without merging**
