### PR TITLE
First refactor PR

### PR DESCRIPTION
**Pull request by SubhradeepSS**

### CODE REVIEW

**Comment by ucalyptus** [comment]
@SubhradeepSS change the PR name

**Comment by SubhradeepSS** [comment]
@ucalyptus As of now,only SparseMatrix data structure is left for porting among all the data structures

**Comment by ucalyptus** [comment]
> @ucalyptus As of now,only SparseMatrix data structure is left for porting among all the data structures

Do this then I shall merge

**Comment by ucalyptus** [comment]
@SubhradeepSS updates?

**Comment by SubhradeepSS** [comment]
> @SubhradeepSS updates?

the last data structure is more than 1000lines code.Therefore taking time

**Comment by SubhradeepSS** [comment]
All the data structures have been ported to python

**Pull request merged**
