### PR TITLE
Readme Update

### LINKED ISSUE #83: Improve README

### LINKED ISSUE #84: Add an SWOC: Important Links Section to README

### PR DESCRIPTION
**Pull request by Avinash-1501**
Fixes #83 
Fixes #84

Added some interactivity to readme page. Now in the 'steps to follow' section, only the main points are visible, and the extra info is under collapse. Also added the SWoC contributor table.
@ucalyptus

### CODE REVIEW

**Comment by ucalyptus** [comment]
@Avinash-1501 LGTM, before I merge, can you share a screenshot(s) of the entire readme? Upload them to the comment section.

**Comment by Avinash-1501** [comment]
@ucalyptus  Here I am attaching the screenshots of new Readme. Thank you

**Comment by sidhu1012** [comment]
LGTM!

**Comment by sidhu1012** [comment]
@ucalyptus Why one test is failing?

**Comment by ucalyptus** [comment]
@sidhu1012 we need to advertise this issue about failing CIs. Can you announce it on the slack?

**Comment by ucalyptus** [comment]
@Avinash-1501 can you DM me on the slack ?

**Comment by ucalyptus** [comment]
@Avinash-1501 update your PR and add your name to the SWOC contrib table. With the link to this PR.

**Comment by ucalyptus** [comment]
@Avinash-1501 update ur PR please

**Comment by ucalyptus** [comment]
@Avinash-1501 a fresh PR would be appreciated.

**Pull request closed without merging**
