### PR TITLE
RecSys Item-Item Similarity Based Recommendations

### PR DESCRIPTION
**Pull request by jaindhairyahere**
Issue no: #8 
Needs improvement. Changes will be done once I get the data.

### CODE REVIEW

**Comment by ucalyptus** [comment]
Can you use a publicly available dataset from UCI Dataset repository instead ? would help any reader to understand how item-item would work on something close to the spotify datasets

**Comment by jaindhairyahere** [comment]
can you export the data frame used in Spotify_Recommendation_System.ipynb?

**Comment by ucalyptus** [comment]
It can't be exported . You need to follow the same procedure for yourself. A spotify account is imperative. Make a playlist and add its playlist ID as mentioned in the nb.

**Comment by ucalyptus** [comment]
@jaindhairyahere updates?

**Comment by jaindhairyahere** [comment]
I'll update in a day

**Comment by ucalyptus** [comment]
@jaindhairyahere ok .

**Comment by jaindhairyahere** [comment]
Hey, very sorry for the delay. My laptop broke down and I could only finish it by now

**Comment by jaindhairyahere** [comment]
Hey!

**Comment by jaindhairyahere** [comment]
I removed the Environment Files

**Comment by jaindhairyahere** [comment]
https://nbviewer.jupyter.org/github/jaindhairyahere/Spotify-Recommendation-Engine/blob/master/Spotify.ipynb
Is this okay?

**Pull request merged**
