### PR TITLE
Issue #85 : Added PCA+SVM

### PR DESCRIPTION
**Pull request by SinghShreya05**
Added PCA+SVM wrt issue 85. Please review the PR. @forkbabu

### CODE REVIEW

**Comment by forkbabu** [comment]
@SinghShreya05 before I merge this, can u send me a colab gist link?

**Comment by forkbabu** [comment]
@SinghShreya05 have you been able to generate a playlist?

**Comment by SinghShreya05** [comment]
Sir in the recommendation portion where you've used tree_grid.best_estimator_ just needs to be changed to svm_grid.best_estimator_
And it'll start generating recommendations. 
@forkbabu 
Currently while redirecting my URL, it's not generating the same link that it did earlier.

**Comment by forkbabu** [comment]
@SinghShreya05 message Sayantan Das (@ucalyptus) on slack. He will tell u how to create a playlist. You need to create an account on Spotify and create an API endpoint. the stuff that u see relating to francocasadei has to be replaced with your info inorder to make it work.

**Pull request closed without merging**
